version: "3"

services:
  redis:
    image: redis:6.0.9-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager